config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  # StaticPages routes
  match '/about', to: 'static_pages#about', via: 'get'
  get '/submission', to: 'static_pages#submission'
  get '/rejected', to: 'static_pages#rejected'
  get '/question_review', to: 'static_pages#question_review'
  get '/grades', to: 'static_pages#grades'
  get '/quiz', to: 'static_pages#quiz'
  get '/grade_quiz', to: 'static_pages#grade_quiz'
  get '/dashboard', to: 'static_pages#dashboard'
  get '/teacher_dashboard', to: 'static_pages#teacher_dashboard'
  get '/petitions', to: 'static_pages#petitions'
  get '/parent', to: 'static_pages#parent'
  get '/lesson', to: 'static_pages#lesson'
  devise_for :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def submission

  end

  def grades

  end

  def question_review

  end

  def quiz

  end

  def rejected
    @comment = params[:comment] ? params[:comment] : "There was no comment"
  end

  def dashboard

  end

  def grade_quiz
  end

  def teacher_dashboard
  end

  def petitions
  end

  def parent
  end

  def lesson
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top header" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag("vvv-brand.png", id: "logo"), root_path %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>
      <ul class="nav navbar-nav navbar-right">
         <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Hunter S. Thompson", dashboard_path %></li>
            <li class="divider"></li>
            <li><%= link_to "Sign Out", '#' %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Vvvacademy
    = stylesheet_link_tag    'application', media: 'all'
    = stylesheet_link_tag '//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    %script{:src => "http://code.highcharts.com/highcharts.js"}
    %script{:src => "http://code.highcharts.com/modules/exporting.js"}
    = render 'layouts/header'
    .container-fluid
      = yield
    %script{:src => "https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"}

app/views/static_pages/_response.html.haml
%form{:role => "form"}
  .form-group
    %label{:for => "Problem"} Problem
    %input.form-control{:type => "text", :value => "3x+4=10"}/
  .form-group#solution-steps
    %label{:for => "solutionStep"}
      Solution Steps
      %a#step{href:"#"} (+)
    %input.form-control{:type => "text", :placeholder => "Solution Step", :value => "There has to be some dummy data"}/
  .form-group
    %label{:for => "solution"} Solution
    %input.form-control{:type => "text", :value => "There has to be some dummy data"}/

  %button.btn.btn-default{:type => "submit"}=link_to "Submit", dashboard_path

app/views/static_pages/_steps.html.haml
%br
%input.form-control{:placeholder => "Solution Step", :type => "text"}/
%br
%input.form-control{:placeholder => "Solution Step", :type => "text"}/
%br
%input.form-control{:placeholder => "Solution Step", :type => "text"}/

app/views/static_pages/_submissionform.html.haml
%br
%br
%h2.text-center Submit Question
%br
  %row
    .col-md-4.col-md-offset-4
      %form{:role => "form"}
        .form-group
          %label{:for => "Problem"} Problem
          %input.form-control{:placeholder => "Enter Problem", :type => "text"}/
        .form-group#solution-steps
          %label{:for => "solutionStep"}
            Solution Steps
            %a#step{href:"#"} (+)
          %input.form-control{:placeholder => "Solution Step", :type => "text"}/
          %br
          %input.form-control{:placeholder => "Solution Step", :type => "text"}/
          %br
          %input.form-control{:placeholder => "Solution Step", :type => "text"}/

        .form-group
          %label{:for => "solution"} Solution
          %input.form-control{:type => "text", :placeholder => "Enter Final Answer"}/

        %button.btn.btn-default{:type => "submit"}=link_to "Submit", dashboard_path

app/views/static_pages/grade_quiz.html.haml
.row
  %h2 Grade Quiz

.modal.fade.bs-example-modal-sm(tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true")
  .modal-dialog.modal-sm
    .modal-content
      .modal-header Comments
      .modal-body
        %form
          %textarea.form-control(rows="3")
      .modal-footer
        .btn.btn-primary(data-dismiss="modal") Save
.row
  .col-md-2
  .col-md-8
    %ul.quiz-tabs.pagination
      %li
        %a(href="#") &laquo;
      %li.active(data-num="1")
        %a(href= "#") 1
      - 16.times do |index|
        %li{:"data-num" => index + 2}
          %a(href= "#")= index + 2
      %li
        %a(href="#") &raquo;
  .col-md-2
.row
  .col-md-2
  .col-md-4.quiz-problem
    %ul.list-group
      %li.list-group-item.clearfix
        %h5.text-center
          Problem
          %span.problem-number 1
        %p.problem-text A 3 by 4 rectangle is inscribed in circle. What is the circumference of the circle?
      %li.list-group-item.clearfix
        %h5.text-center Solution Steps
        %p.well.well-sm studentsolution
      %li.list-group-item.clearfix
        %h5.text-center Answer
        %p.well.well-sm studentanswer
    .pull-left
      %a.btn.btn-danger(href="#" style="opacity: 0.9;" data-toggle="modal" data-target=".bs-example-modal-sm") Incorrect
    .pull-right
      %a.btn.btn-success(href="#") Correct
  .col-md-4.quiz-problem
    %ul.list-group
      %li.list-group-item.clearfix
        %h5.text-center
          Problem
          %span.problem-number 1
        %p.problem-text 3x+4=10
      %li.list-group-item.clearfix
        %h5.text-center Solution Steps
        %p.well.well-sm 1. 3x=10-4
        %p.well.well-sm 2. 3x=6
        %p.well.well-sm 3. x=2
      %li.list-group-item.clearfix
        %h5.text-center Answer
        %p.well.well-sm x=2
  .col-md-2

app/views/static_pages/gradequiz.html.haml
.row
  %h2 Grade Quiz

.modal.fade.bs-example-modal-sm(tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true")
  .modal-dialog.modal-sm
    .modal-content
      .modal-header Comments
      .modal-body
        %form
          %textarea.form-control(rows="3")
      .modal-footer
        .btn.btn-primary(data-dismiss="modal") Save
.row
  .col-md-2
  .col-md-8
    %ul.quiz-tabs.pagination
      %li
        %a(href="#") &laquo;
      %li.active(data-num="1")
        %a(href= "#") 1
      - 19.times do |index|
        %li{:"data-num" => index + 2}
          %a(href= "#")= index + 2
      %li
        %a(href="#") &raquo;
  .col-md-2
.row
  .col-md-2
  .col-md-4.quiz-problem
    %ul.list-group
      %li.list-group-item.clearfix
        %h5.text-center
          Problem
          %span.problem-number 1
        %p.problem-text A 3 by 4 rectangle is inscribed in circle. What is the circumference of the circle?
      %li.list-group-item.clearfix
        %h5.text-center Solution Steps
        %form
          .form-group
            Stuff from Matt
      %li.list-group-item.clearfix
        %h5.text-center Answer
        Stuff from Matt
    .pull-left
      %a.btn.btn-danger(href="#" style="opacity: 0.9;" data-toggle="modal" data-target=".bs-example-modal-sm") Incorrect
    .pull-right
      %a.btn.btn-success(href="#") Correct
  .col-md-4.quiz-problem
    %ul.list-group
      %li.list-group-item.clearfix
        %h5.text-center
          Problem
          %span.problem-number 1
        %p.problem-text 3x+4=10
      %li.list-group-item.clearfix
        %h5.text-center Solution Steps
        %p 1. 3x=10-4
        %p 2. 3x=6
        %p 3. x=2
      %li.list-group-item.clearfix
        %h5.text-center Answer
        x=2
  .col-md-2

app/views/static_pages/lesson.html.haml
%form.form-horizontal.col-md-4
  %fieldset
    .form-group
    %select.form-control#subject
      %option.disabled.selected Subject
      %option(value="1") Algebra 1
      %option Algebra 2
      %option Geometry
      %option Trigonometry
    .form-group
    %select.form-control#lesson
      %option.disabled.selected Lesson
      %option(value="1") Lesson 1
      %option(value="2") Lesson 2
      %option(value="3") Lesson 3
      %option(value="4") Lesson 4
      %option(value="5") Lesson 5
%br
%br
%br

.modal.fade.modal-submit-question(tabindex="-1" role="dialog" aria-hidden="true")
  .modal-dialog
    .modal-content
      .modal-header Submit Problem
      .modal-body
        %form{:role => "form"}
          .form-group
            %label{:for => "Problem"} Problem
            %input.form-control{:placeholder => "Enter Problem", :type => "text"}/
          .form-group#solution-steps
            %label{:for => "solutionStep"}
              Solution Steps
              %a#step{href:"#"} (+)
            %input.form-control{:placeholder => "Solution Step", :type => "text"}/
          .form-group
            %label{:for => "solution"} Solution
            %input.form-control{:type => "text", :placeholder => "Solution Step"}/
      .modal-footer
        %button.btn.btn-primary{:type => "submit"} Submit

.modal.fade.modal-review-question(tabindex="-1" role="dialog" aria-hidden="true")
  .modal-dialog
    .modal-content
      .modal-header Submit Problem
      .modal-body
        .quiz-problem
          %ul.list-group
            %li.list-group-item.clearfix
              %h5.text-center
                Problem
              %p.problem-text 3x+4=10
            %li.list-group-item.clearfix
              %h5.text-center Solution Steps
              %p.well.well-sm 1. 3x=10-4
              %p.well.well-sm 2. 3x=6
              %p.well.well-sm 3. x=2
            %li.list-group-item.clearfix
              %h5.text-center Answer
              %p.well.well-sm x=2
          .panel.panel-default
            .panel-heading
              Question Guidelines
            .panel-body
              .form-group
                %i.fa.fa-thumbs-o-up
                &nbsp
                %i.fa.fa-thumbs-o-down
              %p.checkboxes
                %input.thumbs-up(type="radio" name="radio1")
                &nbsp
                %input.thumbs-down(type="radio" name="radio1")
                &nbsp
                &nbsp
                Contains between 4-6 terms
              %p.checkboxes
                %input.thumbs-up(type="radio" name="radio2")
                &nbsp
                %input.thumbs-down(type="radio" name="radio2")
                &nbsp
                &nbsp
                Only uses the addition/subtraction operands
              %p.checkboxes
                %input.thumbs-up(type="radio" name="radio3")
                &nbsp
                %input.thumbs-down(type="radio" name="radio3")
                &nbsp
                &nbsp
                Uses integers between 0-20
              %p.checkboxes
                %input.thumbs-up(type="radio" name="radio4")
                &nbsp
                %input.thumbs-down(type="radio" name="radio4")
                &nbsp
                &nbsp
                Uses only one variable
              .comments.hidden
                %p.text-center Comments
                %form(action="/rejected" method="GET")
                  %textarea.form-control(rows="3" name="comment" placeholder="Enter an explanation" required="required")
                  .hidden.reject-question(style="margin-top: 5%;")
                    %input.btn.btn-danger.center-block(type="submit" value="Reject Question")
      .modal-footer
        %a.btn.btn-success.hidden.accept-question.center-block(style="margin-top: 5%;" href="#") Approve Question

//#TODO Add Lesson Content
%br
%br
.row
  #content(style="display:none")
    = render 'lesson_content'
%br


.row
%h4 Status
.btn.btn-default.disabled#submit( data-toggle="modal" data-target=".modal-submit-question") Submit Question
.btn.btn-default.disabled#review( data-toggle="modal" data-target=".modal-review-question") Review Question
%a.btn.btn-default.disabled#quiz(href= "/quiz") Take Quiz
%a.btn.btn-default.disabled#grade(href= '/grade_quiz') Grade Quiz
%a.btn.btn-default.disabled#grades(href= '/dashboard') Review Grades


:javascript
  $(function() {
    $('select').change(function() {
      if ($('#subject').val()=="1") {
        $('#content').show();
      };
    });

    $('select').change(function() {
      if ($('#lesson').val()=="5") {
        $('#submit, #review, #quiz, #grade, #grades').addClass('disabled');
      } else if ($('#lesson').val()=="3") {
        $('#submit').removeClass('disabled');
      } else if ($('#lesson').val()=="2") {
        $('#submit').addClass('disabled');
        $('#review').removeClass('disabled');
      } else if ($('#lesson').val()=="1") {
        $('#grades').removeClass('disabled');
        $('#submit, #review').addClass('disabled');
      };
    });
  });

app/views/static_pages/parent.html.haml
%h3 Class Grades
%div.divider
%div.center
	%ul.list-group
		%li.list-group-item
			%span.badge.badgeHeight 78
			Algebra
			.progress.progressMargin
				.progress-bar{:style => "width: 78%"}
		%li.list-group-item
			%span.badge 85
			Geometry
			.progress.progressMargin
				.progress-bar{:style => "width: 85%"}
		%li.list-group-item
			%span.badge 92
			Pre-Calculus
			.progress.progressMargin
				.progress-bar{:style => "width: 92%"}

app/views/static_pages/petitions.html.haml
%div.center

  %a{:href => "/teacher_dashboard"}
    %h1 Teacher Dashboard
  

  %table.table-hover
    %thead
      %tr
        %th.col-md-8.shorterCol
          %h4 Select Subject
        %th.col-md-5
          %ul.nav.nav-pills
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                Algebra
                %span.caret
              %ul.dropdown-menu
                %li
                  %a{"data-toggle" => "tab", :href => ""} Algebra
                %li.divider
                %li
                  %a{"data-toggle" => "tab", :href => ""} Geometry

  %div{:style => "height:25px;"}

.panel.panel-default.center#petition1
  .panel-heading
    %h3.panel-title Pending Petition #314159
    %span.floatR
      %a.btn.btn-success.btn-xs{:href => "#"} Correct
      %a.btn.btn-danger.btn-xs{:href => "#"} Incorrect
  .panel-body
    .row
    %h5.text-center.teacherPetitionProblem 3x = 10-4
    .row
    .col-md-1
    .col-md-5.quiz-problem
      %ul.list-group
        %li.list-group-item.clearfix
          %h5.text-center Solution Submitted
          %p 1. 3x=10-4
          %p 2. 3x=6.0
          %p 3. x=2.0
        %li.list-group-item.clearfix.submittedSol
          %h5.text-center Answer
          x=2.0
    .col-md-5.quiz-problem
      %ul.list-group
        %li.list-group-item.clearfix
          %h5.text-center Answer Key
          %p 1. 3x=10-4
          %p 2. 3x=6
          %p 3. x=2
        %li.list-group-item.clearfix.answerKey
          %h5.text-center Answer
          x=2


.panel.panel-default.center#petition2
  .panel-heading
    %h3.panel-title Pending Petition #314160
    %span.floatR
      %a.btn.btn-success.btn-xs{:href => "#"} Correct
      %a.btn.btn-danger.btn-xs{:href => "#"} Incorrect
  .panel-body
    .row
    %h5.text-center.teacherPetitionProblem 2x = 12-4
    .row
    .col-md-1
    .col-md-5.quiz-problem
      %ul.list-group
        %li.list-group-item.clearfix
          %h5.text-center Solution Submitted
          %p 1. 2x=12-4
          %p 2. 2x=8
          %p 3. x=6
        %li.list-group-item.clearfix.submittedSol
          %h5.text-center Answer
          x=6
    .col-md-5.quiz-problem
      %ul.list-group
        %li.list-group-item.clearfix
          %h5.text-center Answer Key
          %p 1. 2x=12-4
          %p 2. 2x=8
          %p 3. x=4
        %li.list-group-item.clearfix.answerKey
          %h5.text-center Answer
          x=4

app/views/static_pages/question_review.html.haml
.row
  %h2.text-center Question Review
.row
  .col-md-1
  .col-md-5.quiz-problem
    %ul.list-group
      %li.list-group-item.clearfix
        %h5.text-center
          Problem
        %p.problem-text 3x+4=10
      %li.list-group-item.clearfix
        %h5.text-center Solution Steps
        %p.well.well-sm 1. 3x=10-4
        %p.well.well-sm 2. 3x=6
        %p.well.well-sm 3. x=2
      %li.list-group-item.clearfix
        %h5.text-center Answer
        %p.well.well-sm x=2
  .col-md-5
    .panel.panel-default
      .panel-heading
        Question Guidelines
      .panel-body
        .form-group
          %i.fa.fa-thumbs-o-up
          &nbsp
          %i.fa.fa-thumbs-o-down
        %p.checkboxes
          %input.thumbs-up(type="radio" name="radio1")
          &nbsp
          %input.thumbs-down(type="radio" name="radio1")
          &nbsp
          &nbsp
          Contains between 4-6 terms
        %p.checkboxes
          %input.thumbs-up(type="radio" name="radio2")
          &nbsp
          %input.thumbs-down(type="radio" name="radio2")
          &nbsp
          &nbsp
          Only uses the addition/subtraction operands
        %p.checkboxes
          %input.thumbs-up(type="radio" name="radio3")
          &nbsp
          %input.thumbs-down(type="radio" name="radio3")
          &nbsp
          &nbsp
          Uses integers between 0-20
        %p.checkboxes
          %input.thumbs-up(type="radio" name="radio4")
          &nbsp
          %input.thumbs-down(type="radio" name="radio4")
          &nbsp
          &nbsp
          Uses only one variable
        .comments.hidden
          %p.text-center Comments
          %form(action="/rejected" method="GET")
            %textarea.form-control(rows="3" name="comment" placeholder="Enter an explanation" required="required")
            .hidden.reject-question(style="margin-top: 5%;")
              %input.btn.btn-danger.center-block(type="submit" value="Reject Question")
        %a.btn.btn-success.hidden.accept-question.center-block(style="margin-top: 5%;" href="#") Approve Question
  .col-md-1

app/views/static_pages/rejected.html.haml
%h1.text-center Rejection Notice
%row
  %br
  .col-md-4.col-md-offset-2
    = render 'response'
  .col-md-4
    %h3 Peer Review Notes
    = @comment
    %hr
      %ul

app/views/static_pages/teacher_dashboard.html.erb
<h1>Teacher Dashboard</h1>
<br/>
<form class="form-horizontal col-md-4">
  <fieldset>
    <div class="form-group">
      <select class="form-control" id="subject">
        <option disabled selected>Subject</option>
        <option value="1">Algebra 1</option>
        <option>Algebra 2</option>
        <option>Geometry</option>
        <option>Statistic</option>
      </select>
    </div>
    <div class="form-group">
      <select class="form-control" id="lesson">
        <option disabled selected>Lesson</option>
        <option>Lesson 1</option>
        <option>Lesson 2</option>
        <option>Lesson 3</option>
        <option>Lesson 4</option>
        <option value="1">Lesson 5</option>
      </select>
    </div>
  </fieldset>
</form>

<br/><br/><br/><br/><br/>

<div id="show-this-stuff" style="display:none">
	<h3>Quiz Grades</h3>
	<div class="row">
		<div class="col-md-8">
			<div id="container">
			</div>
		</div>
	</div>


<br/><br/>

<h3>Quiz Questions</h3>
<form class="form-horizontal col-md-4">
  <fieldset>
    <div class="form-group">
      <select class="form-control" id="subject">
        <option selected>Top 3</option>
        <option>Top 5</option>
        <option>Top 10</option>
        <option>Top 25</option>
      </select>
    </div>
  </fieldset>
</form>
<div class="row">
	<div class="col-md-8">
		<%= render 'static_pages/questions' %>
	</div>
</div>

<br/>

<!-- handle petitions -->
<a class="btn btn-info btn-lg" href="/petitions" style="margin-bottom:75px">
  Handel Petitions
</a>

<!-- Button trigger modal -->
<button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#createTest" style="margin-bottom:75px">
  Create New Test
</button>


</div>

<div class="modal fade" id="createTest" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Create Test</h4>
      </div>
      <div class="modal-body">
				<form class="form-horizontal">
				  <fieldset>
				    <div class="form-group">
				      <select class="form-control" id="quality" autofocus>
				        <option disabled selected>Quality</option>
				        <option value="1">Top 5</option>
				        <option>Top 10</option>
				        <option>Top 25</option>
				        <option>Top 50</option>
				      </select>
				    </div>
				    <div class="form-group">
				      <select class="form-control" id="level">
				        <option disabled selected>Level</option>
				        <option value="1">Class</option>
				        <option>School</option>
				        <option>District</option>
				        <option>County</option>
				        <option>State</option>
				        <option>Country</option>
				      </select>
				    </div>
				    <div class="form-group">
				      <select class="form-control" id="level">
				        <option value="" disabled selected>Time</option>
				        <option value="1">Past 3 lessons</option>
				        <option>Past 5 lessons</option>
				        <option>Past 1 week</option>
				        <option>Past 2 weeks</option>
				        <option>Past 4 weeks</option>
				        <option>Cumulative</option>
				      </select>
				    </div>
				    <div class="form-group">
							<input type="text" class="form-control" placeholder="Quantity">
				    </div>
				  </fieldset>
				</form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Create</button>
      </div>
    </div>
  </div>
</div>

<script>
$(document).ready(function() {
	$('select').change(function() {
		if ($('#subject').val()=="1" && $('#lesson').val()=="1") {
			$('#show-this-stuff').show();
		}
	})
});
$(function () {
    $('#container').highcharts({
        chart: {
            type: 'column'
        },
        title: {
            text: ''
        },
        xAxis: {
            categories: [
                'Quiz 1',
                'Quiz 2',
                'Quiz 3',
                'Quiz 4',
                'Quiz 5'
            ]
        },
        yAxis: {
            min: 0,
            max: 100,
            title: {
                text: 'Grade (%)'
            }
        },
        tooltip: {
            headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
            pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                '<td style="padding:0"><b>{point.y:.1f} pts</b></td></tr>',
            footerFormat: '</table>',
            shared: true,
            useHTML: true
        },
        plotOptions: {
            column: {
                pointPadding: 0.2,
                borderWidth: 0
            }
        },
        series: [{
            name: 'Average',
            data: [84.5, 78.9, 90.1, 75.2, 80.2]

        }, {
            name: 'Highest',
            data: [98, 89, 100, 84, 93]

        }, {
            name: 'Lowest',
            data: [60, 45, 74, 40, 55]
        }]
    });
});
</script>

app/views/static_pages/teacher_dashboard.html.haml
%div.center

  %h1 Teacher Dashboard

  %div{:style => "height:25px;"}

  %table.table-hover    
    %thead
      %tr
        %th.col-md-8.shorterCol
          %h4 Select Subject
        %th.col-md-5
          %ul.nav.nav-pills
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                Algebra
                %span.caret
              %ul.dropdown-menu
                %li
                  %a{"data-toggle" => "tab", :href => ""} Algebra
                %li.divider
                %li
                  %a{"data-toggle" => "tab", :href => ""} Geometry
      %tr
        %th.col-md-8.shorterCol
          %h4 Select Lesson
        %th.col-md-8
          %ul.nav.nav-pills
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                Solving for one variable using Addition 
                %span.caret
              %ul.dropdown-menu
                %li
                  %a#complete{"data-toggle" => "tab", :href => ""} Solving for one variable using addition
                %li.divider
                %li
                  %a#progress{"data-toggle" => "tab", :href => ""} Solving for one variable using subtraction
        %th.btn.btn-success.btn-sm.teacherProgress Completed

  %div.completedQuestionBank

  %div.inProgressQuestionBank

app/views/static_pages/teacherdashboard.html.haml
:css
  .teacherLesson {
   height: 60px;
  }
  .teacherProgress {
   width: 117px;
  }
  .center {
    margin-top: 40px;
    margin-left: auto;
    margin-right: auto;
    width: 70%;
  }
  .shorterCol {
    width: 200px;
  }
%div.center

  %h1 Teacher Dashboard

  %table.table-hover
    %thead
      %tr
        %th.col-md-8.shorterCol
          %h4 Select Subject
        %th.col-md-5
          %ul.nav.nav-pills
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                Algebra
                %span.caret
              %ul.dropdown-menu
                %li
                  = link_to "Algebra", quiz_path
                %li.divider
                %li
                  %a{"data-toggle" => "tab", :href => ""} Geometry

  %div{:style => "height:25px;"}


  %table.table-hover
    %thead
      %tr
        %th.col-md-8
          %h4 Lesson
        %th.col-md-4
          %h4 Progress
    %tbody
      %tr.teacherLesson
        %td.col-md-8 Solving for one variable using addition
        %td.col-md-4
          .btn.btn-success.teacherProgress Completed
      %tr.teacherLesson
        %td.col-md-8 Solving for one variable using subtraction
        %td.col-md-4
          .btn.btn-primary.teacherProgress In Progress
      %tr.teacherLesson
        %td.col-md-8 Solving for one variable using multiplication
        %td.col-md-4
          .btn.btn-default.teacherProgress Assign Later
      %tr.teacherLesson
        %td.col-md-8 Solving for one variable using multiplication
        %td.col-md-4
          .btn.btn-default.teacherProgress Assign Later